"""
bloom_india/setup.py
====================
Interactive first-time setup wizard.
Asks for your data directory and writes config.yaml.

Run:
    python -m bloom_india.setup
    # or
    python setup.py
"""

import os
import sys
import shutil
from pathlib import Path


BANNER = """
╔══════════════════════════════════════════════════════════════╗
║                                                              ║
║   bloom_india  —  NSE/BSE PIT Data Platform                 ║
║   First-time setup                                           ║
║                                                              ║
╚══════════════════════════════════════════════════════════════╝
"""

DEFAULTS = {
    "base_dir":       "~/bloom_india_data",
    "hold_days":      "20",
    "n_long":         "5",
    "n_short":        "5",
    "terminal_port":  "8501",
}


def ask(prompt: str, default: str, validator=None) -> str:
    while True:
        val = input(f"  {prompt} [{default}]: ").strip()
        if not val:
            val = default
        if validator:
            err = validator(val)
            if err:
                print(f"  ✗ {err}")
                continue
        return val


def validate_dir(val: str) -> str:
    """Return error string or empty string."""
    try:
        p = Path(val).expanduser().resolve()
        if p.exists() and not p.is_dir():
            return f"{p} exists and is not a directory"
        return ""
    except Exception as e:
        return str(e)


def validate_int(lo=1, hi=9999):
    def _v(val):
        try:
            n = int(val)
            if n < lo or n > hi:
                return f"Must be between {lo} and {hi}"
            return ""
        except ValueError:
            return "Must be an integer"
    return _v


def main():
    print(BANNER)

    # ── Find config.yaml template ─────────────────────────────────────────────
    repo_root    = Path(__file__).parent.parent
    template     = repo_root / "config.yaml"
    config_dest  = repo_root / "config.yaml"
    example_file = repo_root / "config.yaml.example"

    if not template.exists() and not example_file.exists():
        print("✗ Could not find config.yaml or config.yaml.example.")
        print("  Make sure you're running this from the bloom_india repo root.")
        sys.exit(1)

    if example_file.exists() and not config_dest.exists():
        shutil.copy(example_file, config_dest)

    # ── Check if already configured ───────────────────────────────────────────
    if config_dest.exists():
        print(f"  Found existing config: {config_dest}")
        overwrite = input("  Overwrite? [y/N]: ").strip().lower()
        if overwrite != "y":
            print("  Setup cancelled. Your existing config.yaml is unchanged.")
            sys.exit(0)

    print("\n  Where should bloom_india store downloaded and processed data?")
    print("  This will contain raw XBRL files, bhavcopy archives, and databases.")
    print("  You need ~10-20 GB free for full Nifty 50 history.\n")

    base_dir = ask(
        "Data directory",
        DEFAULTS["base_dir"],
        validate_dir,
    )
    base_path = Path(base_dir).expanduser().resolve()

    print(f"\n  Data will be stored at: {base_path}")
    print("  Subdirectories will be created automatically:\n")
    print(f"    {base_path}/raw/          ← downloaded XBRL, bhavcopy files")
    print(f"    {base_path}/raw/xbrl/     ← XBRL filing cache")
    print(f"    {base_path}/raw/bhavcopy/ ← NSE daily price files")
    print(f"    {base_path}/db/           ← processed parquet databases")

    print("\n  Backtest defaults (can be overridden per-run):\n")
    hold  = ask("Default hold days",  DEFAULTS["hold_days"],  validate_int(1, 252))
    nlong = ask("Default n_long",     DEFAULTS["n_long"],     validate_int(1, 25))
    nshrt = ask("Default n_short",    DEFAULTS["n_short"],    validate_int(1, 25))
    port  = ask("Terminal port",      DEFAULTS["terminal_port"], validate_int(1024, 65535))

    # ── Write config.yaml ─────────────────────────────────────────────────────
    config_content = f"""# bloom_india/config.yaml
# Generated by setup.py — edit freely.
# This file is in .gitignore — your paths stay private.

storage:
  base_dir: "{base_dir}"

  # Set any of these to override the default (base_dir/raw/*, base_dir/db/*)
  raw_dir: null
  xbrl_dir: null
  bhavcopy_dir: null
  announce_dates_file: null
  db_dir: null
  price_db: null
  fundamental_db: null
  corp_actions_db: null

fetch:
  request_delay_sec: 0.5
  max_retries: 3
  timeout_sec: 20
  user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36"

universe:
  default_index: "NIFTY 50"
  supported:
    - "NIFTY 50"
    - "NIFTY 100"
    - "NIFTY NEXT 50"

data:
  price_floor:       "2010-01-01"
  fundamental_floor: "2018-04-01"

backtest:
  default_hold_days: {hold}
  default_n_long: {nlong}
  default_n_short: {nshrt}
  min_stocks_for_signal: 4

terminal:
  port: {port}
  host: "localhost"
"""

    with open(config_dest, "w") as f:
        f.write(config_content)

    # ── Create directories ────────────────────────────────────────────────────
    for subdir in ["raw/xbrl", "raw/bhavcopy", "db"]:
        (base_path / subdir).mkdir(parents=True, exist_ok=True)

    print(f"""
  ✓ Config written to: {config_dest}
  ✓ Directories created under: {base_path}

  Next steps:
  ────────────────────────────────────────────────────
  1. Build price database:
       python -m bloom_india.scripts.build_price_db

  2. Build fundamental database:
       python -m bloom_india.scripts.build_fundamental_db

  3. Launch terminal:
       streamlit run bloom_india/terminal/app.py

  Or use the API directly:
       from bloom_india.api import get_fundamentals, get_ohlcv
       df = get_fundamentals("2024-01-25")
  ────────────────────────────────────────────────────
""")


if __name__ == "__main__":
    main()
